apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shadows_of_judgement
spec:
  template:
    spec:
      containers:
        - image: <+artifact.image>
          ports:
            - containerPort: 8080