pipeline:
  identifier: Build_daviddc5_game__shadows_of_judgement_1788442912046
  name: Build game--shadows-of-judgement
  orgIdentifier: default
  projectIdentifier: shadowsofjudgement
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1788442749671
        repoName: daviddc5/game--shadows-of-judgement
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    connectorRef: shadows_of_judgement_GCP_project
                    image: node:20-bookworm
                    shell: Sh
                    command: npm install
                    privileged: false
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    connectorRef: shadows_of_judgement_GCP_project
                    image: node:20-bookworm
                    shell: Sh
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
